runtime: python
env: flex
entrypoint: gunicorn -b :$PORT ingestapp:app --timeout 120
service: default
manual_scaling:
  instances: 1

env_variables:
    CLOUD_STORAGE_BUCKET: data-science-on-gcp.marcm.dev

handlers:
- url: /ingest
  script: ingestapp.app

- url: /.*
  script: ingestapp.app